// <auto-generated />
using System;
using ApplicationsManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationsManager.Migrations
{
    [DbContext(typeof(AppManagerContext))]
    [Migration("20230517111951_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationsManager.Entitiy.ApplicationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 17, 14, 49, 51, 613, DateTimeKind.Local).AddTicks(2962),
                            Name = "صندوقک"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 5, 17, 14, 49, 51, 613, DateTimeKind.Local).AddTicks(2967),
                            Name = "ویژیتو"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 5, 17, 14, 49, 51, 613, DateTimeKind.Local).AddTicks(2968),
                            Name = "سفارشگیر"
                        });
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.ApplicationVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApplicationTypeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("code")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationTypeId");

                    b.ToTable("ApplicationVersions");
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2023, 5, 17, 14, 49, 51, 613, DateTimeKind.Local).AddTicks(2813),
                            Mobile = "09364142953",
                            Name = "احمدی",
                            Password = "123456",
                            Username = "ahmadi"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2023, 5, 17, 14, 49, 51, 613, DateTimeKind.Local).AddTicks(2830),
                            Mobile = "09364142953",
                            Name = "اکبری",
                            Password = "123456",
                            Username = "akbari"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2023, 5, 17, 14, 49, 51, 613, DateTimeKind.Local).AddTicks(2831),
                            Mobile = "09364142953",
                            Name = "حسینی",
                            Password = "123456",
                            Username = "hosseini"
                        });
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("planId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("planId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationTypeId = 1L,
                            CreatedDate = new DateTime(2023, 5, 17, 14, 49, 51, 613, DateTimeKind.Local).AddTicks(2988),
                            CustomerId = 1L,
                            EndTime = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StartTime = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            planId = 1L
                        });
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.SubscriptionActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUseTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("bigint");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionActivities");
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.SubscriptionPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Days = 10,
                            MaxUsers = 5,
                            Name = "ده روزه"
                        },
                        new
                        {
                            Id = 2L,
                            Days = 30,
                            MaxUsers = 5,
                            Name = "یکماهه"
                        });
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45be2da5-932e-49ff-b923-ae9b34b81512"),
                            FName = "حمید",
                            LName = "اکبری",
                            Password = "123456",
                            Role = 1,
                            Username = "hamid"
                        },
                        new
                        {
                            Id = new Guid("bb07c0ab-ff0d-496e-8341-3a404f211a15"),
                            FName = "میلاد",
                            LName = "انجم شعاع",
                            Password = "123456",
                            Role = 0,
                            Username = "milad"
                        });
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.ApplicationVersion", b =>
                {
                    b.HasOne("ApplicationsManager.Entitiy.ApplicationType", "ApplicationType")
                        .WithMany("ApplicationVersions")
                        .HasForeignKey("ApplicationTypeId");

                    b.Navigation("ApplicationType");
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.Subscription", b =>
                {
                    b.HasOne("ApplicationsManager.Entitiy.ApplicationType", "ApplicationType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ApplicationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationsManager.Entitiy.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationsManager.Entitiy.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("planId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationType");

                    b.Navigation("Customer");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.SubscriptionActivity", b =>
                {
                    b.HasOne("ApplicationsManager.Entitiy.Subscription", "Subscription")
                        .WithMany("SubscriptionActivities")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.ApplicationType", b =>
                {
                    b.Navigation("ApplicationVersions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.Customer", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.Subscription", b =>
                {
                    b.Navigation("SubscriptionActivities");
                });

            modelBuilder.Entity("ApplicationsManager.Entitiy.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
